#!/usr/bin/env python3
"""Generate a simple HTML report for the Oracle → Databricks simulation results.

Reads `outputs/oracle-databricks/migration_plan/migration_plan.json` and
`compatibility_report.json` and renders a minimal HTML summary.
"""

import json
from pathlib import Path
from datetime import datetime


TEMPLATE_PATH = Path('templates/dashboard.template.html')


def render_from_template(title: str, description: str, plan: dict, compat: dict) -> str:
    tpl = TEMPLATE_PATH.read_text(encoding='utf-8')

    # Basic replacements
    tpl = tpl.replace('{{PAGE_TITLE}}', title)
    tpl = tpl.replace('{{PAGE_DESCRIPTION}}', description)
    tpl = tpl.replace('{{LOADING_TEXT}}', 'Rendering report')
    tpl = tpl.replace('{{LOGO_TEXT}}', 'Migration')
    tpl = tpl.replace('{{LOGO_SUFFIX}}', 'Suite')
    tpl = tpl.replace('{{NAV_LINKS}}', '<a href="#top">Top</a>')
    tpl = tpl.replace('{{EYEBROW}}', 'Simulation')
    tpl = tpl.replace('{{HERO_TITLE}}', 'Oracle Exadata → Databricks')
    tpl = tpl.replace('{{HERO_SUBTITLE}}', f"Migration simulation generated at {plan.get('created_at', '')}")
    tpl = tpl.replace('{{HERO_BUTTONS}}', '<a class="btn btn-primary" href="#meter">Overview</a>')

    # Meter cells
    tables = plan.get('tables_to_migrate', 0)
    warnings = len(compat.get('warnings', []))
    plan_cells = f"""
    <div class="meter-cell"><div class="val">{tables}</div><div class="lbl">Tables to migrate</div></div>
    <div class="meter-cell"><div class="val ember">{warnings}</div><div class="lbl">Compatibility warnings</div></div>
    <div class="meter-cell"><div class="val">{len(plan.get('steps', []))}</div><div class="lbl">Planned steps</div></div>
    <div class="meter-cell"><div class="val">{plan.get('migration_id','')}</div><div class="lbl">Migration ID</div></div>
    """
    tpl = tpl.replace('{{METER_TITLE}}', 'Simulation Overview')
    tpl = tpl.replace('{{METER_SUBTITLE}}', 'Auto-generated')
    tpl = tpl.replace('{{METER_CELLS}}', plan_cells)

    # Main sections: compatibility table and plan dump
    warnings_html = ''
    if compat.get('warnings'):
        warnings_rows = ''.join(f"<tr><td class=\"mono\">{w}</td></tr>" for w in compat['warnings'])
        warnings_html = f"<section><div class=\"sec-label\">Compatibility Warnings</div><table class=\"data-table\"><thead><tr><th>Warning</th></tr></thead><tbody>{warnings_rows}</tbody></table></section>"
    else:
        warnings_html = '<section><div class="sec-label">Compatibility</div><p class="sec-intro">No warnings detected.</p></section>'

    # Render migration plan as clean HTML tables: summary + steps
    plan_summary_rows = []
    plan_summary_rows.append(f"<tr><td class=\"mono\">Migration ID</td><td>{plan.get('migration_id','')}</td></tr>")
    plan_summary_rows.append(f"<tr><td class=\"mono\">Source</td><td>{plan.get('source','')}</td></tr>")
    plan_summary_rows.append(f"<tr><td class=\"mono\">Target</td><td>{plan.get('target','')}</td></tr>")
    plan_summary_rows.append(f"<tr><td class=\"mono\">Created At</td><td>{plan.get('created_at','')}</td></tr>")
    plan_summary_rows.append(f"<tr><td class=\"mono\">Tables To Migrate</td><td>{plan.get('tables_to_migrate',0)}</td></tr>")
    plan_summary = '<table class="data-table"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>' + ''.join(plan_summary_rows) + '</tbody></table>'

    steps = plan.get('steps', [])
    steps_rows = ''
    if steps:
        for s in steps:
            step_no = s.get('step', '')
            name = s.get('name', '')
            status = s.get('status', '')
            steps_rows += f"<tr><td class=\"mono\">{step_no}</td><td>{name}</td><td><span class=\"badge\">{status}</span></td></tr>"
        steps_table = '<table class="data-table"><thead><tr><th>#</th><th>Step</th><th>Status</th></tr></thead><tbody>' + steps_rows + '</tbody></table>'
    else:
        steps_table = '<p class="sec-intro">No steps defined.</p>'

    plan_html = f"<section><div class=\"sec-label\">Migration Plan - Summary</div>{plan_summary}</section><section><div class=\"sec-label\">Migration Plan - Steps</div>{steps_table}</section>"

    main = warnings_html + plan_html
    tpl = tpl.replace('{{MAIN_SECTIONS}}', main)

    tpl = tpl.replace('{{CTA_TITLE}}', 'Next steps')
    tpl = tpl.replace('{{CTA_SUBTITLE}}', 'Run validation checks or export artifacts to Databricks')
    tpl = tpl.replace('{{CTA_LINK}}', '#')
    tpl = tpl.replace('{{CTA_BUTTON_TEXT}}', 'Validate')
    tpl = tpl.replace('{{FOOTER_LEFT}}', 'Generated by Data Migration Suite')
    tpl = tpl.replace('{{FOOTER_RIGHT}}', datetime.now().isoformat())

    return tpl


def main():
    in_dir = Path('outputs/oracle-databricks/migration_plan')
    out_dir = Path('outputs/oracle-databricks/reports')
    out_dir.mkdir(parents=True, exist_ok=True)

    plan_p = in_dir / 'migration_plan.json'
    compat_p = in_dir / 'compatibility_report.json'
    if not plan_p.exists() or not compat_p.exists():
        print('Run the simulator first.')
        return

    plan = json.loads(plan_p.read_text(encoding='utf-8'))
    compat = json.loads(compat_p.read_text(encoding='utf-8'))

    html = render_from_template('Oracle → Databricks Simulation', 'Simulation report generated by suite', plan, compat)
    (out_dir / 'migration_report.html').write_text(html, encoding='utf-8')

    print('✅ Report generated at', out_dir / 'migration_report.html')


if __name__ == '__main__':
    main()
